plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.mod_group_id

base {
	archivesName = project.mod_id
}

repositories {
	maven {
		name = "Parchment Mappings"
		url = uri("https://maven.parchmentmc.org")
		content {
			includeGroupAndSubgroups("org.parchmentmc")
		}
	}
	maven {
		name = "Modrinth"
		url = uri("https://api.modrinth.com/maven")
		content {
			includeGroupAndSubgroups("maven.modrinth")
		}
	}
	maven {
		name = "Terraformers (Mod Menu)"
		url = uri("https://maven.terraformersmc.com/releases/")
		content {
			includeGroupAndSubgroups("com.terraformersmc")
			includeGroupAndSubgroups("dev.emi")
		}
	}
	maven {
		name = "Fabricators of Create (Snapshots)"
		url = uri("https://mvn.devos.one/snapshots")
		content {
			includeGroupAndSubgroups("net.createmod")
			includeGroupAndSubgroups("dev.engine-room")
			includeGroupAndSubgroups("io.github.fabricators_of_create")
			includeGroupAndSubgroups("com.simibubi")
		}
	}
	maven {
		name = "Fabricators of Create (Releases)"
		url = uri("https://mvn.devos.one/releases")
		content {
			includeGroupAndSubgroups("net.createmod")
			includeGroupAndSubgroups("dev.engine-room")
			includeGroupAndSubgroups("io.github.fabricators_of_create")
			includeGroupAndSubgroups("com.simibubi")
		}
	}
	maven {
		name = "Create, Ponder, Flywheel"
		url = uri("https://maven.createmod.net")
		content {
			includeGroupAndSubgroups("net.createmod")
			includeGroupAndSubgroups("dev.engine-room")
		}
	}
	maven {
		name = "Fuzs Mod Resources"
		url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
		content {
			includeGroupAndSubgroups("fuzs")
		}
	}
	maven {
		name = "reach-entity-attributes"
		url = uri("https://maven.jamieswhiteshirt.com/libs-release")
		content {
			includeGroupAndSubgroups("com.jamieswhiteshirt")
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Cassian's Maven"
				url = uri("https://maven.cassian.cc")
			}
		}
		filter {
			includeGroupAndSubgroups("cc.cassian")
		}
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation("com.terraformersmc:modmenu:18.0.0-beta.1")

	implementation("maven.modrinth:create-fly:${create_version}")
	implementation("cc.cassian.rrv:reliable-recipe-viewer-fabric:$rrv_version")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.mod_id
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}